fix(function): améliorer la gestion des options d'installation en simplifiant le flux de validation et en ajoutant des messages d'erreur

diff --git a/function b/function
--- a/function
+++ b/function
@@ -392,131 +392,131 @@ function prompt_install_options(){
             export VERSION_SELECT REP_GLPI DOWNLOADLINK REP_BACKUP_COMPRESS INVOKING_HOME GLPI_CLI_VERSION
             # Lancement de la mise à jour
             run_sequence "update"
-        elif [[ "${INSTALL_OR_UPDATE}" == 1 ]]; then
-            tags=""
-            # Récupère les tags au format X.Y.Z
-            tags=$(curl -s "${API_URL}" | jq -r '.[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | grep -v -E '(rc|beta|alpha)' | uniq | head -n 16) 
-            local args=() first=ON number=1 version_map=()
-            while IFS= read -r tag; do
-                args+=("${number}" "GLPI ${tag}" "${first}")
-                version_map+=("${tag}")
-                first=OFF
-                number=$((number + 1))
-            done <<< "${tags}"
-            exec 3>&1
-            VERSION_SELECT=$(dialog --backtitle "$MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL" --title "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_INSTALL}" \
-            --radiolist "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_RADIOLIST_INSTALL}" 23 50 8 "${args[@]}" 3>&1 1>&2 2>&3)
-            local rc=$?
-            exec 3>&-
-            if [ "${rc}" -ne 0 ]; then
-                warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}"
-                return 1
-            fi
-            # VERSION_SELECT retourne le tag choisi (ici nous utilisons des tags numériques mapping -> version_map)
-            if ! [[ "${VERSION_SELECT}" =~ ^[0-9]+$ ]]; then
-                warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_INVALID} ${VERSION_SELECT}"
-                return 1
-            fi
-            # Convertir le numéro choisi en index du tableau (0-based)
-            local index=""
-            index=$((VERSION_SELECT - 1))
-            # Récupérer le vrai tag correspondant
-            VERSION_SELECT="${version_map[$index]}"
-            if [ $index -lt 0 ] || [ $index -ge ${#version_map[@]} ]; then
-                warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_OUT_OF_RANGE} ${index}"
-                return 1
-            fi
-            WIDTH_REP=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_REP} ))
-            WIDTH_DB_HOST=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_HOST} ))
-            WIDTH_DB_NAME=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_NAME} ))
-            WIDTH_DB_USER=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_USER} ))
-            WIDTH=$(( WIDTH_REP > WIDTH_DB_HOST ? WIDTH_REP : WIDTH_DB_HOST ))
-            WIDTH=$(( WIDTH > WIDTH_DB_NAME ? WIDTH : WIDTH_DB_NAME ))
-            WIDTH=$(( WIDTH > WIDTH_DB_USER ? WIDTH : WIDTH_DB_USER ))
-            WIDTH=$(( WIDTH + 6 ))
-            local _def_rep="" rep_glpi="" _def_db_host="" db_host="" _def_db_name="" db_name="" _def_db_user="" db_user=""
-            if [ -n "${FIND_REP_GLPI}" ]; then
-                _def_rep="${REP_GLPI:-${FIND_REP_GLPI}}"
-            else
-                _def_rep="${REP_GLPI:-/var/www/html/glpi/}"
-            fi
-            local _def_db_host="${DB_HOST:-localhost}" _def_db="${DB_NAME:-glpi}" _def_user="${DB_USER:-glpi_user}"
-            while true; do
-                exec 3>&1
-                form=$(dialog --backtitle "$MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL" --title "$MSG_PARAM_TITLE" \
-                    --form "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_PARAM_1} ${VERSION_SELECT} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_PARAM_2}" 18 68 8 \
-                    "📁 ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_REP}"     1 2 "${_def_rep}"     1 ${WIDTH} 20 40 \
-                    "🖥️ ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_HOST}" 3 2 "${_def_db_host}" 3 ${WIDTH} 20 20 \
-                    "🗄️ ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_NAME}" 5 2 "${_def_db}"      5 ${WIDTH} 20 20 \
-                    "👤 ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_USER}" 7 2 "${_def_user}"    7 ${WIDTH} 20 20 \
-                    2>&1 1>&3)
-                rc=$?
-                exec 3>&-
-                # Transformer les lignes du formulaire en variables
-                IFS=$'\n' read -r rep_glpi db_host db_name db_user <<< "$form"
-                rep_glpi="${rep_glpi#"${rep_glpi%%[![:space:]]*}"}"; rep_glpi="${rep_glpi%"${rep_glpi##*[![:space:]]}"}"
-                db_host="${db_host#"${db_host%%[![:space:]]*}"}"; db_host="${db_host%"${db_host##*[![:space:]]}"}"
-                db_name="${db_name#"${db_name%%[![:space:]]*}"}"; db_name="${db_name%"${db_name##*[![:space:]]}"}"
-                db_user="${db_user#"${db_user%%[![:space:]]*}"}"; db_user="${db_user%"${db_user##*[![:space:]]}"}"
-                rep_glpi="${rep_glpi//[^A-Za-z0-9_\/.-]/_}"
-                db_host="${db_host//[^A-Za-z0-9_\/.-]/_}"
-                db_name="${db_name//[^A-Za-z0-9_]/_}"
-                db_user="${db_user//[^A-Za-z0-9_]/_}"
-                [ -z "$rep_glpi" ] && rep_glpi="$_def_rep"
-                [ -z "$db_host" ] && db_host="$_def_db_host"
-                [ -z "$db_name" ] && db_name="$_def_db"
-                [ -z "$db_user" ] && db_user="$_def_user"
-                if [[ ! "$db_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
-                    db_name="glpi_${db_name}"
-                fi
-                rep_glpi="${rep_glpi//\\//}"
-                if [ -z "${rep_glpi}" ] || [[ "${rep_glpi}" != /* ]]; then
-                    rep_glpi="${_def_rep}"
-                fi
-                rep_glpi="$(printf '%s' "${rep_glpi}" | sed -E 's#/{2,}#/#g')"
-                REP_GLPI="${rep_glpi%/}/"
-                DB_HOST="$db_host"
-                DB_NAME="$db_name"
-                DB_USER="$db_user"
-                # Si annulation ou ESC
-                if [[ $rc -ne 0 ]]; then
-                    warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}"
-                    dialog --title "${MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL}" --msgbox "${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}" 7 60
-                    exit 1
-                fi
-                # --- VALIDATIONS ---
-                # Répertoire d’installation
-                if ! validate_glpi_path "$REP_GLPI"; then
-                    continue
-                fi
-                # Hôte de la base de données
-                if ! validate_db_host "$DB_HOST"; then
-                    continue
-                fi
-                # Nom de la base de données
-                if ! validate_db_name "$DB_NAME"; then
-                    continue
-                fi
-                # Utilisateur de la base de données
-                if ! validate_db_user "$DB_USER"; then
-                    continue
-                fi
-                # Si tout est valide
-                break
-            done
-            # Assignation des valeurs finales
-            local DOWNLOADLINK="https://github.com/glpi-project/glpi/releases/download/${VERSION_SELECT}/glpi-${VERSION_SELECT}.tgz"
-            local DB_HOST="${DB_HOST}"
-            local REP_GLPI="${REP_GLPI}"
-            local DB_NAME="${DB_NAME}"
-            local DB_USER="${DB_USER}"
-            local INVOKING_HOME="${PWD}"
-            local TIMEZONE="${TIMEZONE:-UTC}"
-            local VERSION_SELECT="${VERSION_SELECT}"
-            export DOWNLOADLINK DB_HOST REP_GLPI DB_NAME DB_USER INVOKING_HOME TIMEZONE
-            # Lancement de l’installation
-            run_sequence "install"
         fi
+    elif [[ "${INSTALL_OR_UPDATE}" == 1 ]]; then
+        tags=""
+        # Récupère les tags au format X.Y.Z
+        tags=$(curl -s "${API_URL}" | jq -r '.[].name' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | grep -v -E '(rc|beta|alpha)' | uniq | head -n 16) 
+        local args=() first=ON number=1 version_map=()
+        while IFS= read -r tag; do
+            args+=("${number}" "GLPI ${tag}" "${first}")
+            version_map+=("${tag}")
+            first=OFF
+            number=$((number + 1))
+        done <<< "${tags}"
+        exec 3>&1
+        VERSION_SELECT=$(dialog --backtitle "$MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL" --title "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_INSTALL}" \
+        --radiolist "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_RADIOLIST_INSTALL}" 23 50 8 "${args[@]}" 3>&1 1>&2 2>&3)
+        local rc=$?
+        exec 3>&-
+        if [ "${rc}" -ne 0 ]; then
+            warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}"
+            return 1
+        fi
+        # VERSION_SELECT retourne le tag choisi (ici nous utilisons des tags numériques mapping -> version_map)
+        if ! [[ "${VERSION_SELECT}" =~ ^[0-9]+$ ]]; then
+            warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_INVALID} ${VERSION_SELECT}"
+            return 1
+        fi
+        # Convertir le numéro choisi en index du tableau (0-based)
+        local index=""
+        index=$((VERSION_SELECT - 1))
+        # Récupérer le vrai tag correspondant
+        VERSION_SELECT="${version_map[$index]}"
+        if [ $index -lt 0 ] || [ $index -ge ${#version_map[@]} ]; then
+            warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_OUT_OF_RANGE} ${index}"
+            return 1
+        fi
+        WIDTH_REP=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_REP} ))
+        WIDTH_DB_HOST=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_HOST} ))
+        WIDTH_DB_NAME=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_NAME} ))
+        WIDTH_DB_USER=$(( ${#MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_USER} ))
+        WIDTH=$(( WIDTH_REP > WIDTH_DB_HOST ? WIDTH_REP : WIDTH_DB_HOST ))
+        WIDTH=$(( WIDTH > WIDTH_DB_NAME ? WIDTH : WIDTH_DB_NAME ))
+        WIDTH=$(( WIDTH > WIDTH_DB_USER ? WIDTH : WIDTH_DB_USER ))
+        WIDTH=$(( WIDTH + 6 ))
+        local _def_rep="" rep_glpi="" _def_db_host="" db_host="" _def_db_name="" db_name="" _def_db_user="" db_user=""
+        if [ -n "${FIND_REP_GLPI}" ]; then
+            _def_rep="${REP_GLPI:-${FIND_REP_GLPI}}"
+        else
+            _def_rep="${REP_GLPI:-/var/www/html/glpi/}"
+        fi
+        local _def_db_host="${DB_HOST:-localhost}" _def_db="${DB_NAME:-glpi}" _def_user="${DB_USER:-glpi_user}"
+        while true; do
+            exec 3>&1
+            form=$(dialog --backtitle "$MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL" --title "$MSG_PARAM_TITLE" \
+                --form "${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_PARAM_1} ${VERSION_SELECT} ${MSG_PROMPT_INSTALL_OPTIONS_VERSION_TITLE_PARAM_2}" 18 68 8 \
+                "📁 ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_REP}"     1 2 "${_def_rep}"     1 ${WIDTH} 20 40 \
+                "🖥️ ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_HOST}" 3 2 "${_def_db_host}" 3 ${WIDTH} 20 20 \
+                "🗄️ ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_NAME}" 5 2 "${_def_db}"      5 ${WIDTH} 20 20 \
+                "👤 ${MSG_PROMPT_INSTALL_OPTIONS_PARAM_DB_USER}" 7 2 "${_def_user}"    7 ${WIDTH} 20 20 \
+                2>&1 1>&3)
+            rc=$?
+            exec 3>&-
+            # Transformer les lignes du formulaire en variables
+            IFS=$'\n' read -r rep_glpi db_host db_name db_user <<< "$form"
+            rep_glpi="${rep_glpi#"${rep_glpi%%[![:space:]]*}"}"; rep_glpi="${rep_glpi%"${rep_glpi##*[![:space:]]}"}"
+            db_host="${db_host#"${db_host%%[![:space:]]*}"}"; db_host="${db_host%"${db_host##*[![:space:]]}"}"
+            db_name="${db_name#"${db_name%%[![:space:]]*}"}"; db_name="${db_name%"${db_name##*[![:space:]]}"}"
+            db_user="${db_user#"${db_user%%[![:space:]]*}"}"; db_user="${db_user%"${db_user##*[![:space:]]}"}"
+            rep_glpi="${rep_glpi//[^A-Za-z0-9_\/.-]/_}"
+            db_host="${db_host//[^A-Za-z0-9_\/.-]/_}"
+            db_name="${db_name//[^A-Za-z0-9_]/_}"
+            db_user="${db_user//[^A-Za-z0-9_]/_}"
+            [ -z "$rep_glpi" ] && rep_glpi="$_def_rep"
+            [ -z "$db_host" ] && db_host="$_def_db_host"
+            [ -z "$db_name" ] && db_name="$_def_db"
+            [ -z "$db_user" ] && db_user="$_def_user"
+            if [[ ! "$db_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
+                db_name="glpi_${db_name}"
+            fi
+            rep_glpi="${rep_glpi//\\//}"
+            if [ -z "${rep_glpi}" ] || [[ "${rep_glpi}" != /* ]]; then
+                rep_glpi="${_def_rep}"
+            fi
+            rep_glpi="$(printf '%s' "${rep_glpi}" | sed -E 's#/{2,}#/#g')"
+            REP_GLPI="${rep_glpi%/}/"
+            DB_HOST="$db_host"
+            DB_NAME="$db_name"
+            DB_USER="$db_user"
+            # Si annulation ou ESC
+            if [[ $rc -ne 0 ]]; then
+                warn "${ICON_WARN} ${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}"
+                dialog --title "${MSG_PROMPT_INSTALL_OPTIONS_BACKTITLE_INSTALL}" --msgbox "${MSG_PROMPT_INSTALL_OPTIONS_ABORT_INSTALL}" 7 60
+                exit 1
+            fi
+            # --- VALIDATIONS ---
+            # Répertoire d’installation
+            if ! validate_glpi_path "$REP_GLPI"; then
+                continue
+            fi
+            # Hôte de la base de données
+            if ! validate_db_host "$DB_HOST"; then
+                continue
+            fi
+            # Nom de la base de données
+            if ! validate_db_name "$DB_NAME"; then
+                continue
+            fi
+            # Utilisateur de la base de données
+            if ! validate_db_user "$DB_USER"; then
+                continue
+            fi
+            # Si tout est valide
+            break
+        done
+        # Assignation des valeurs finales
+        local DOWNLOADLINK="https://github.com/glpi-project/glpi/releases/download/${VERSION_SELECT}/glpi-${VERSION_SELECT}.tgz"
+        local DB_HOST="${DB_HOST}"
+        local REP_GLPI="${REP_GLPI}"
+        local DB_NAME="${DB_NAME}"
+        local DB_USER="${DB_USER}"
+        local INVOKING_HOME="${PWD}"
+        local TIMEZONE="${TIMEZONE:-UTC}"
+        local VERSION_SELECT="${VERSION_SELECT}"
+        export DOWNLOADLINK DB_HOST REP_GLPI DB_NAME DB_USER INVOKING_HOME TIMEZONE
+        # Lancement de l’installation
+        run_sequence "install"
     fi
     debug "${ICON_DEBUG} ${MSG_DEBUG_END}"
 }
