fix(function): ajouter un trap pour gérer les erreurs dans check_install

diff --git a/function b/function
--- a/function
+++ b/function
@@ -395,6 +395,7 @@ function compatible() {
 # Vérifie si GLPI est installé ou pas
 function check_install() {
     warn "$(date '+%F %T') [$$][DEBUG:check_install] Entrée dans la fonction" >> "${LOGFILE}"
+    trap 'echo "[ERREUR] Ligne $LINENO : commande échouée" >> "$ERRORFILE"; exit 1' ERR
     local FIND_REP_GLPI=""
     local installed_version=""
     local version_file=""
