Refactor GLPI installation script and update French language file
- Moved the distribution check to occur after prompting for installation options in the glpi-install script to ensure a smoother installation process.
- Updated French language strings in fr_lang.ini to improve formatting by adding quotes around the version variable for better readability.

diff --git a/glpi-install b/glpi-install
--- a/glpi-install
+++ b/glpi-install
@@ -17,16 +17,16 @@ trap 'on_error' ERR
 load_language # Fichier de langue
 # Regarde si la distribution est conforme
 info "${MSG_START_SCRIPT}" >> "${DEBUGFILE}"
-info "${MSG_CHECK_DISTRIBUTION}" >> "${DEBUGFILE}"
-if ! check_distro; then
-   dialog --title "${MSG_DIALOG_ERROR_TITLE}" --msgbox "${MSG_DISTRO_CHECK_FAILED}" 6 50
-    error "${MSG_DISTRO_CHECK_ERROR}" 2>> "${ERRORFILE}"
-    exit 1
-fi
 info "${MSG_PROMPT_INSTALL_OPTIONS}" >> "${DEBUGFILE}"
 if ! prompt_install_options; then # Demande les options d'installation
     dialog --title "${MSG_DIALOG_ERROR_TITLE}" --msgbox "${MSG_PROMPT_OPTIONS_FAILED}" 6 70
     error "${MSG_PROMPT_OPTIONS_ERROR}" 2>> "${ERRORFILE}"
+    exit 1
+fi
+info "${MSG_CHECK_DISTRIBUTION}" >> "${DEBUGFILE}"
+if ! check_distro; then
+   dialog --title "${MSG_DIALOG_ERROR_TITLE}" --msgbox "${MSG_DISTRO_CHECK_FAILED}" 6 50
+    error "${MSG_DISTRO_CHECK_ERROR}" 2>> "${ERRORFILE}"
     exit 1
 fi
 info "${MSG_CHECK_INSTALL}" >> "${DEBUGFILE}"
